{{- if and (.Values.enabled) (.Values.ingress.enabled) -}}
{{- $context := .Values -}}
{{- $fullName := include "nginx.fullname" . -}}
{{- $ingress := .Values.ingress -}}
{{- $domain := .Values.ingress.domain | default .Values.global.ingress.domain  -}}
{{- range $index, $ingressMapping := $ingress.ingressMapping }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  {{- if eq (len $ingress.ingressMapping) 1 }}
  name: {{ printf "%s-ingress" $fullName }}
  {{- else }}
  name: {{ printf "%s-ingress-%d" $fullName (add1 $index) }}
  {{- end }}
  annotations:
    {{- toYaml $ingress.additionalAnnotations | nindent 4 }}
spec:
  ingressClassName: {{ $ingress.ingressClassName | quote }}
  {{- if $ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $ingressMapping.host | quote }}
    secretName: {{ $ingress.tls.secretName }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ $ingressMapping.path }}
        pathType: {{ $ingressMapping.pathType }}
        backend:
          service:
            name: {{ printf "%s-service" $fullName }}
            port:
              number: {{ $context.port }}
  {{- if $ingressMapping.host }}
    {{- if $domain }}
    host: {{ printf "%s.%s" $ingressMapping.host $domain }}
    {{- else }}
    host: {{ printf "%s" $ingressMapping.host }}
    {{- end }}
  {{- end }}
{{ printf "---" }}
{{- end }}
{{- end -}}
