name: Match chart version and push to ACR

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
    uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@master
    secrets: inherit
    with:
      context: docker-image
  
  build_and_push_helm:
    uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@master
    secrets: inherit
