name: Bump Helm Chart Version

on:
  workflow_dispatch:
  push:
    branches:
      - '*'  # Adjust the branch as needed

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Set up Helm
        uses: Azure/setup-helm@v1
        with:
          version: 'v3.12.0'

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          npx semantic-release
