name: Match chart version and push to ACR

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_helm_and_push:
    uses: MapColonies/shared-workflows/.github/workflows/release-and-push-helm.yaml@master
    secrets: inherit

  build_and_push_docker:
    uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@master
    secrets: inherit
    with:
      context: docker-image    
