name: Match chart version and push to ACR

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
    uses: MapColonies/shared-workflows/.github/workflows/release-and-push-helm.yaml@remove_permissions
    secrets: inherit
