name: Update Helm Docs

on:
  push:
    branches:
      - '*'

jobs:
  update-helm-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Run helm-docs
      run: |
        pwd
        ls -a
        cd .github/workflows
        chmod +x ./update-helm-docs.sh
        ./update-helm-docs.sh

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Helm documentation"
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}