split_clients "$otel_trace_id" $ratio_sampler {
              {{ .Values.opentelemetry.ratio }}%              on;
              *                off;
}

server {
    listen 8080;
    server_name  localhost;

    # Include external configuration file if "additionalConf" is set to true in values.yaml
    {{- if .Values.nginx.additionalConf.enabled }}
    include /etc/nginx/conf.d/{{ .Values.nginx.additionalConf.fileName }};
    {{- end }}

    # In case you use "add_header" in the location block, these "add_header" will be ignored!
    add_header 'Access-Control-Max-Age' '{{ .Values.nginx.maxAge | default "7200" }}';
    add_header 'Access-Control-Allow-Origin' {{ .Values.nginx.allowedOrigins | default "*" | squote }};
    add_header 'Access-Control-Allow-Headers' {{ .Values.nginx.allowedHeaders | default "*" | squote }};

    location / {
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' {{ .Values.nginx.allowedOrigins | default "*" | squote }};
        add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' {{ .Values.nginx.allowedHeaders | default "*" | squote }};
        #
        # Tell client that this pre-flight info is valid for x seconds, default is 1 day (86400s)
        #
        add_header 'Access-Control-Max-Age' '{{ .Values.nginx.optionsMaxAge | default "86400" }}';
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }

      {{ include "nginx.otelTrace" . | nindent 8 }}

      set $original_method $request_method;
      set $original_args $args;

      {{ if .Values.authorization.enabled }}
      set $domain {{ .Values.authorization.domain }};
      auth_request /_validate_jwt;

      otel_span_attr opa.result $opa_result;
      otel_span_attr opa.reason $opa_reason;
      {{ end }}

      proxy_pass http://{{ .Values.backend.host }}:{{ .Values.backend.port }};
    }

    {{ if .Values.authorization.enabled }}
    location = /_validate_jwt {
      internal;

      js_content auth.opaAuth;
    }

    location = /opa {
      internal;

      proxy_set_header Content-Type application/json;
      proxy_pass {{ .Values.authorization.url }};
    }    
    {{ end }}

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
